// <auto-generated />
using System;
using DalDonation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DalDonation.Migrations
{
    [DbContext(typeof(DonationContext))]
    partial class DonationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("DalDonation.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescriptionCurrency");

                    b.HasKey("Id");

                    b.ToTable("currency");
                });

            modelBuilder.Entity("DalDonation.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CodeSugCurrency");

                    b.Property<int>("CodeSugYeshut");

                    b.Property<string>("ConditionDonation");

                    b.Property<float?>("ConversionRate");

                    b.Property<float>("CountDonation");

                    b.Property<string>("ReasonDonation");

                    b.Property<string>("YeshutName");

                    b.HasKey("DonationId");

                    b.ToTable("donation");
                });

            modelBuilder.Entity("DalDonation.SugYeshut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescriptionYeshut");

                    b.HasKey("Id");

                    b.ToTable("sugYeshut");
                });
#pragma warning restore 612, 618
        }
    }
}
